name: Build & deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Setup Elm environment
        uses: JorelAli/setup-elm@v5

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build:prod

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        working_directory: ./tf
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        working_directory: ./tf
        run: terraform init

      - name: Terraform Validate
        id: validate
        working_directory: ./tf
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working_directory: ./tf
        run: terraform plan -no-color
        continue-on-error: true
